clean: true
objc: true
readme: README.md
theme: fullwidth
output: docs.zh-cn
sdk: iphonesimulator
readme: README.zh-cn.md
umbrella_header: .jazzy.zh-cn/MovieousLive/MovieousLive.h
framework_root: .jazzy.zh-cn